---
title: "Proposal"
author: "Ellen Ahlness and Wesley Zuidema"
date: "October 12, 2016"
output: pdf_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE, cache = TRUE)
```


```{r}
# Load Packages
library(ggplot2)
library(dplyr)
```

```{r}
# Load data
load("../data/wvs_data.rdata")
wvs_data <- WVS_Longitudinal_1981_2014_R_v2015_04_18
```

```{r fig.cap = "Immigration Policy"}
# Histogram of IV - Responses to Change
ggplot(filter(wvs_data, E143 > 0)) +
  geom_histogram(aes(E143), binwidth = 1) + 
  scale_x_continuous(breaks=seq(0,max(wvs_data$E143), 1)) +
  labs(x = "Immigration Policy (1 - 5, where 1 is most open and 5 is most restrictive)", y = "Count")
```

```{r fig.cap = "Acceptance of Change"}
# Histogram of IV - Responses to Change
ggplot(filter(wvs_data, E047 > 0)) +
  geom_histogram(aes(E047), binwidth = 1) + 
  scale_x_continuous(breaks=seq(0,max(wvs_data$E047), 1)) +
  labs(x = "Acceptance of Change (1 - 10)", y = "Count")
```

```{r fig.cap = "Age"}
# Histogram of Age
ggplot(filter(wvs_data, X003 > 0)) +
  geom_histogram(aes(X003), binwidth = 1) + 
  scale_x_continuous(breaks=seq(0,max(wvs_data$X003), 5)) +
  labs(x = "Age", y = "Count")
```

```{r fig.cap = "Income Level"}
# Histogram of income
ggplot(filter(wvs_data, X047 > 0)) +
  geom_histogram(aes(X047), binwidth = 1) + 
  scale_x_continuous(breaks=seq(0,max(wvs_data$X047), 1)) +
  labs(x = "Income Level (1 - 10)", y = "Count")
```

```{r fig.cap = "Sex"}
# Histogram of gender
ggplot(filter(wvs_data, X001 > 0)) +
  geom_histogram(aes(X001), binwidth = 1) + 
  scale_x_continuous(breaks=seq(0,max(wvs_data$X001), 1)) +
  labs(x = "Sex (1 = Male, 2 = Female)", y = "Count")
```

```{r fig.cap = "Marital Status"}
# Histogram of Marital Status
ggplot(filter(wvs_data, X007 > 0)) +
  geom_histogram(aes(X007), binwidth = 1) + 
  scale_x_continuous(breaks=seq(0,max(wvs_data$X007), 1)) +
  labs(x = "Marital Status (1 = Married, 6 = Never Married)", y = "Count")
```

